[tool.black]
line-length = 100
exclude = ['migrations',]

[tool.flake8]
ignore = ['W503',]
max-line-length = 100

[tool.isort]
profile = 'black'
line_length = 100
lines_after_imports = 2
skip_gitignore = true
extend_skip = ['migrations',]
