# Generated by Django 4.2.3 on 2023-07-25 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='дата смерти')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('summary', models.TextField(help_text='Введите кратное описание книги', max_length=1000, verbose_name='описание')),
                ('isbn', models.CharField(help_text='13-значный международный <a href="https://www.isbn-international.org/content/what-isbn">код ISBN</a>', max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.author', verbose_name='автор')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите жанр книги (например Фантастика, Поэзия и т.д.)', max_length=120, verbose_name='жанр')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID данного экземпляра книги.', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=100, verbose_name='издательство')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='доступна после')),
                ('status', models.CharField(blank=True, choices=[('m', 'На обслуживании'), ('o', 'На руках'), ('a', 'Доступна'), ('r', 'Зарезервирована')], default='m', help_text='Доступность книги', max_length=1, verbose_name='статус')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='catalog.book', verbose_name='книга')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Выберите жанр книги', related_name='books', to='catalog.genre'),
        ),
    ]
